name: Update Homebrew Cask
description: Update the Homebrew cask formula with a new version and SHA, then commit and push

inputs:
  version:
    description: "Release version"
    required: true

runs:
  using: composite
  steps:
    - name: Update cask formula
      shell: bash
      run: |
        set -e
        SHA256=$(shasum -a 256 Bowzer-${{ inputs.version }}.zip | awk '{print $1}')
        sed -i '' "s/version \".*\"/version \"${{ inputs.version }}\"/" Casks/bowzer.rb
        sed -i '' "s/sha256 \".*\"/sha256 \"${SHA256}\"/" Casks/bowzer.rb

    - name: Commit and push cask update
      shell: bash
      run: |
        set -e
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add Casks/bowzer.rb
        git commit -m "chore: update cask to v${{ inputs.version }}"
        git push origin HEAD:main
